name: CI Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      VITE_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0

      - name: Print Node version (for debug)
        run: node -v

      - name: Install dependencies
        run: npm ci

      - name: Print environment variables (temporary)
        run: |
          echo "SUPABASE_URL: $VITE_SUPABASE_URL"
          echo "SUPABASE_KEY: $VITE_SUPABASE_ANON_KEY"
       

      - name: Run Vitest with verbose output
        run: npm run test -- --run --reporter verbose
